spring:
  application:
    name: certchain

  datasource:
    url: ${CERT_DB_URL:jdbc:postgresql://localhost:5432/certichain}
    username: ${CERT_DB_USERNAME:certichain}
    password: ${CERT_DB_PASSWORD:certichain_password}
    driver-class-name: org.postgresql.Driver


  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

server:
  port: 6969





certichain:
  keystore:
    path: ./keystore/ssdcve.p12
    password: ${SSDCVE_KEYSTORE_PASSWORD:change-me-keystore-password}
  jwt:
    secret: ${SSDCVE_JWT_SECRET:change-me-in-production-minimum-32-bytes-long!!!}
    access-token-ttl-minutes: 60
  auth:
    cookie-secure: false
    refresh-token-ttl-days: 7

ssdcve:
  keystore:
    path: ./keystore/ssdcve.p12
    password: ${SSDCVE_KEYSTORE_PASSWORD:change-me-keystore-password}
  ipfs:
    api-url: http://localhost:5001



logging:
  level:
    web: debug
    db: debug
