spring:
  application:
    name: certchain

  datasource:
    url: ${CERT_DB_URL:jdbc:postgresql://localhost:5432/certichain}
    username: ${CERT_DB_USERNAME:certichain}
    password: ${CERT_DB_PASSWORD:certichain_password}
    driver-class-name: org.postgresql.Driver

  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

server:
  port: 6969

certichain:
  jwt:
    secret: ${SSDCVE_JWT_SECRET:change-me-in-production-minimum-32-bytes-long!!!}
    access-token-ttl-minutes: 60
  auth:
    cookie-secure: false
    refresh-token-ttl-days: 7
  swagger:
    enabled: true

ssdcve:
  keystore:
    path: ./keystore/ssdcve.p12
    password: ${SSDCVE_KEYSTORE_PASSWORD:change-me-keystore-password}
  ipfs:
    api-url: http://localhost:5001
  blockchain:
    rpc-url: ${SSDCVE_BLOCKCHAIN_RPC_URL:http://localhost:8545}
    from-address: ${SSDCVE_BLOCKCHAIN_FROM:0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266}
    chain-id: ${SSDCVE_BLOCKCHAIN_CHAIN_ID:31337}

logging:
  level:
    web: info